### ISSUE TITLE
verify_ca not working

### ISSUE THREAD

**Issue by mohamedhafez** [trilogy-libraries/trilogy#202]
In my Rails 6.1 application, I have 

```ruby
ssl_mode: verify_ca
sslca: /opt/homebrew/var/mysql/ca.pem
```

It works with the mysql2 adapter, but when i try to switch to trilogy I get the following error when trying to make a request of the database:

> /Users/mohamed/.rbenv/versions/truffleruby+graalvm-24.1.0/lib/gems/gems/activerecord-trilogy-adapter-3.1.2/lib/active_record/connection_adapters/trilogy_adapter.rb:84:in `new_client': trilogy_ssl_upgrade: SSL Error: certificate verify failed (ActiveRecord::ConnectionNotEstablished)

Does Trilogy not support `verify_ca`? (it works just fine once I switch to `ssl_mode: required`)

**Comment by mohamedhafez** [comment]
(I wasn't sure where the correct place to file this bug was, there's a duplicate at: https://github.com/trilogy-libraries/activerecord-trilogy-adapter/issues/74, feel free to close the one that's in the wrong place)

**Comment by mohamedhafez** [comment]
Same error occurs under Rails 7.2, Ruby 3.3.5:

```
trilogytest $ bin/rails db:migrate
bin/rails aborted!
ActiveRecord::ConnectionNotEstablished: trilogy_ssl_upgrade: SSL Error: certificate verify failed (ActiveRecord::ConnectionNotEstablished)
```

**Comment by composerinteralia** [comment]
It should work, but the trilogy options are a little different than the mysql2 options. It'd be good for us to have better documentation with all the available options, but in the meantime here's an example from the test suite: https://github.com/trilogy-libraries/trilogy/blob/204ee88219a633521a981b7169d0a41308e65b0b/contrib/ruby/test/ssl_test.rb#L159

**Comment by mohamedhafez** [comment]
Ah!! Yeah thank you yeah that did work!! yeah documentation might be nice for others migrating from mysql2, or even directly mapping mysql2 options to their trilogy equivalent in database.yml to make migration more automatic, but thats just a suggestion and belongs in another issue anyway, closing this, thanks again!
