### ISSUE TITLE
`_t` suffix is reserved for system types.

### ISSUE THREAD

**Issue by ioquatix** [trilogy-libraries/trilogy#205]
> The requirement that additional types defined in this section end in "_t" was prompted by the problem of name space pollution. It is difficult to define a type (where that type is not one defined by POSIX.1-2017) in one header file and use it in another without adding symbols to the name space of the program. To allow implementors to provide their own types, all conforming applications are required to avoid symbols ending in "_t", which permits the implementor to provide additional types. Because a major use of types is in the definition of structure members, which can (and in many cases must) be added to the structures defined in POSIX.1-2017, the need for additional types is compelling.

https://pubs.opengroup.org/onlinepubs/9699919799/xrat/V4_xsh_chap02.html#tag_22_02_12

**Comment by jhawthorn** [comment]
As I'm sure you're aware it's an extremely common convention in C libraries. All of our typedefs are prefixed with `trilogy_` anyways and that doesn't seem like a name POSIX is likely to claim so I don't see value in fixing this.

**Comment by ioquatix** [comment]
Being common doesn't make it correct. But fair enough, it's unlikely to cause issues.
