### ISSUE TITLE
undefined method `size' for an instance of Trilogy::Result

### ISSUE THREAD

**Issue by pasl** [trilogy-libraries/trilogy#206]
Hi,

I'm unsure if Trilogy is designed as a direct replacement for Mysql2 without compatibility issues, but I've encountered one.

```ruby
undefined method `size' for an instance of Trilogy::Result
```

With MySQL2

```ruby
> results = ActiveRecord::Base.connection.execute("select sn from products")
   (12.8ms)  select sn from products
 => 
#<Mysql2::Result:0x00000001623d13d8
... 
> results.size
 => 27706 
> results.count
 => 27706 

```

With Trilogy

```ruby
> results = ActiveRecord::Base.connection.execute("select sn from products")
   (38.7ms)  select sn from products
 => 
#<Trilogy::Result:0x0000000127554f60
... 
> results.size
...gems/irb-1.14.0/lib/irb.rb:1285:in `full_message': undefined method `size' for an instance of Trilogy::Result (NoMethodError)

results.size
       ^^^^^
3.3.4 :003 > results.count
 => 27706 
```

I am using : trilogy (2.9.0) and mysql2 (0.5.6)

Thank you

**Comment by nickborromeo** [comment]
It looks like in `mysql2`, `size` is an alias to `count`. I added this alias in https://github.com/trilogy-libraries/trilogy/pull/209. Let see what the maintainers say 🤞

**Comment by jhawthorn** [comment]
I think it makes sense for us to add `size` but in general Trilogy does not intend to implement the methods mysql2 has 1:1
