### ISSUE TITLE
prometheus metrics for SQL via discourse/prometheus_exporter

### ISSUE THREAD

**Issue by vfiset** [trilogy-libraries/trilogy#207]
Since we have been using Trilogy in favor of Mysql2 we've lost the prometheus metrics we used to have through [discourse/prometheus_exporter](https://github.com/discourse/prometheus_exporter).

Their [code](https://github.com/discourse/prometheus_exporter/blob/main/lib/prometheus_exporter/middleware.rb#L29-L32) is as below:
```
      if defined? Mysql2::Client
        MethodProfiler.patch(Mysql2::Client, [:query], :sql, instrument: config[:instrument])
        MethodProfiler.patch(Mysql2::Statement, [:execute], :sql, instrument: config[:instrument])
        MethodProfiler.patch(Mysql2::Result, [:each], :sql, instrument: config[:instrument])
      end
```

How could one achieve the same in the context of Trilogy? 

I am merely an infra person, I can't find the equivalent in Trilogy be able to open a PR on their repo so it's supported.

**Comment by composerinteralia** [comment]
I don't know the library well, but I'd think something like this would get it most of the way there:


```rb
      if defined? Trilgoy
        MethodProfiler.patch(Trilogy, [:query], :sql, instrument: config[:instrument])
      end
```

**Comment by vfiset** [comment]
Ok thanks for the quick reply @composerinteralia ! 

I assume that only Trilgoy.query can be instrumented since Trilgoy does not expose methods similar to `execute` and `each` that we see in the snippet from `Mysql2`

**Comment by composerinteralia** [comment]
We don't (currently) support prepared statements, so nothing to do for that one.

We do have [`each` and `each_hash](https://github.com/trilogy-libraries/trilogy/blob/d22ed280f1b5358d54c3bebb905445779ff38f3b/contrib/ruby/lib/trilogy/result.rb#L9-L29)`, but I'm not sure there's anything worth instrumenting in there? `rows` is populated eagerly within `Trilogy.query`, so there's really not much going on in these methods. It looks like mysq2 works differently—where putting together the rows happens lazily inside the [`each` method](https://github.com/brianmario/mysql2/blob/f6a9b68b42a51d1a370403f11eb88527dcb42dc6/ext/mysql2/result.c#L1065).
