### ISSUE TITLE
TypeError: wrong argument type Integer (expected String) 

### ISSUE THREAD

**Issue by MisterBowie** [trilogy-libraries/trilogy#211]
When I execute `rails db:create`, I get TypeError: wrong argument type Integer (expected String)

The trace is as follows:
** Invoke db:create (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:load_config
** Execute db:create
TypeError: wrong argument type Integer (expected String)
Couldn't create 'store_development' database. Please check your configuration.
bin/rails aborted!
ActiveRecord::StatementInvalid: TypeError: wrong argument type Integer (expected String) (ActiveRecord::StatementInvalid)
/Users/vv/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/trilogy-2.9.0/lib/trilogy.rb:18:in `_connect'
/Users/vv/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/trilogy-2.9.0/lib/trilogy.rb:18:in `initialize'
/Users/vv/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/activerecord-7.1.5/lib/active_record/connection_adapters/trilogy_adapter.rb:59:in `new'
/Users/vv/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/activerecord-7.1.5/lib/active_record/connection_adapters/trilogy_adapter.rb:59:in `new_client'
/Users/vv/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/activerecord-7.1.5/lib/active_record/connection_adapters/trilogy_adapter.rb:197:in `connect'
/Users/vv/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/activerecord-7.1.5/lib/active_record/connection_adapters/trilogy_adapter.rb:205:in `reconnect'
/Users/vv/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/activerecord-7.1.5/lib/active_record/connection_adapters/abstract_adapter.rb:685:in `block in reconnect!'
/Users/vv/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/activesupport-7.1.5/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
/Users/vv/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/activerecord-7.1.5/lib/active_record/connection_adapters/abstract_adapter.rb:684:in `reconnect!'
/Users/vv/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/activerecord-7.1.5/lib/active_record/connection_adapters/abstract_adapter.rb:786:in `block in verify!'
/Users/vv/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/activesupport-7.1.5/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
/Users/vv/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/activerecord-7.1.5/lib/active_record/connection_adapters/abstract_adapter.rb:777:in `verify!'
/Users/vv/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/activerecord-7.1.5/lib/active_record/connection_adapters/abstract_adapter.rb:794:in `connect!'
/Users/vv/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/activerecord-7.1.5/lib/active_record/connection_adapters/abstract_adapter.rb:1000:in `block in with_raw_connection'
/Users/vv/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/activesupport-7.1.5/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'

**Comment by MisterBowie** [comment]
rails: 7.1.5
trilogy: 2.9.0
ruby: 3.3.1

**Comment by composerinteralia** [comment]
You've got a key somewhere in your database configuration file (e.g. `config/database.yml`) that is using an `Integer` where Trilogy expects a `String`. I'm not sure from the error message which key it is—so you'll probably have to do some more digging to figure that out. (If you are switching over from the `mysql2` gem, note that the Trilogy options are quite similar but not identical).

**Comment by MisterBowie** [comment]
我已经解决了，原因是数据库的密码为'123456'导致的，

**Comment by MisterBowie** [comment]
> You've got a key somewhere in your database configuration file (e.g. `config/database.yml`) that is using an `Integer` where Trilogy expects a `String`. I'm not sure from the error message which key it is—so you'll probably have to do some more digging to figure that out. (If you are switching over from the `mysql2` gem, note that the Trilogy options are quite similar but not identical).

I have resolved the issue. The reason was due to the database password being '123456',
