### ISSUE TITLE
Fix flaky tests

### ISSUE THREAD

**Issue by kamil-gwozdz** [trilogy-libraries/trilogy#76]
So far I only saw flakes in the CI:

- [ ] [`SslTest#test_raise_proper_invalid_ssl_state [/app/contrib/ruby/test/ssl_test.rb:137]`](https://github.com/github/trilogy/actions/runs/5001954428/jobs/8961314209)
- [ ] [`ClientTest#test_cast_exception_during_query_does_not_close_the_connection [/app/contrib/ruby/test/client_test.rb:561]`](https://github.com/github/trilogy/actions/runs/5001954428/jobs/8961315215)
- [ ] [`ClientTest#test_close_terminate_parent_connection [/Users/runner/work/trilogy/trilogy/contrib/ruby/test/client_test.rb:900]`](https://github.com/github/trilogy/actions/runs/5001954427/jobs/8961314602)

**Comment by bensheldon** [comment]
I think these flakes may have been fixed by https://github.com/trilogy-libraries/trilogy/pull/112

Please continue to document flakes and reopen if I'm wrong or we discover anything new.
